site_name: xTen documentation
site_description: >-
  Welcome to xTen! xTen makes it easy to incorporate AI tools into your extensions — try it out today!
theme:
  name: material
nav:
  - Home: index.md
  - Problem description and design criteria : problem.md
  - Software outline: outline.md 
  - Functions:
    - Summarize: docs/plugins/summarizer
    - Recommender: docs/plugins/recommender
    - OpenAI Plugin: docs/plugins/openAiPlugins
      - Plugin Builder: docs/plugins/openAiPlugins/plugin builder
    - Chatbot: docs/plugins/chatbot
